# Segmenting and Clustering Neighborhoods in Toronto

## Problem 1 Getting the data

In [8]:
pip install beautifulsoup4

Collecting beautifulsoup4
  Downloading https://files.pythonhosted.org/packages/3b/c8/a55eb6ea11cd7e5ac4bacdf92bac4693b90d3ba79268be16527555e186f0/beautifulsoup4-4.8.1-py3-none-any.whl (101kB)
Collecting soupsieve>=1.2 (from beautifulsoup4)
  Downloading https://files.pythonhosted.org/packages/81/94/03c0f04471fc245d08d0a99f7946ac228ca98da4fa75796c507f61e688c2/soupsieve-1.9.5-py2.py3-none-any.whl
Installing collected packages: soupsieve, beautifulsoup4
Successfully installed beautifulsoup4-4.8.1 soupsieve-1.9.5
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

In [9]:
pip install lxml

Collecting lxml
  Downloading https://files.pythonhosted.org/packages/20/8e/f9c5042b5526b732d9e6c9402d87659584448d020b16a889a07f7f0eb0a8/lxml-4.4.1-cp37-cp37m-win32.whl (3.3MB)
Installing collected packages: lxml
Successfully installed lxml-4.4.1
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

In [10]:
pip install html5lib

Collecting html5lib
  Downloading https://files.pythonhosted.org/packages/a5/62/bbd2be0e7943ec8504b517e62bab011b4946e1258842bc159e5dfde15b96/html5lib-1.0.1-py2.py3-none-any.whl (117kB)
Requirement already satisfied: webencodings in c:\users\trupti\appdata\local\programs\python\python37-32\lib\site-packages (from html5lib) (0.5.1)
Requirement already satisfied: six>=1.9 in c:\users\trupti\appdata\local\programs\python\python37-32\lib\site-packages (from html5lib) (1.12.0)
Installing collected packages: html5lib
Successfully installed html5lib-1.0.1
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

In [11]:
pip install requests

Collecting requests
  Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
Collecting certifi>=2017.4.17 (from requests)
  Downloading https://files.pythonhosted.org/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl (154kB)
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests)
  Downloading https://files.pythonhosted.org/packages/b4/40/a9837291310ee1ccc242ceb6ebfd9eb21539649f193a7c8c86ba15b98539/urllib3-1.25.7-py2.py3-none-any.whl (125kB)
Collecting idna<2.9,>=2.5 (from requests)
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
Installing collected packages: certifi, chardet, urllib3, idna, requests
Successfully installed certifi-2019.9.11 chardet-3.0.4 idna-2.8 requests-2.22.0 urllib3-1.25.7
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

In [2]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

In [4]:
source = requests.get('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M').text
soup = BeautifulSoup(source, 'lxml')

In [5]:
table = soup.find_all('table')[0]

In [6]:
df = pd.read_html(str(table))[0]

In [7]:
df

    Postcode           Borough          Neighbourhood
0        M1A      Not assigned           Not assigned
1        M2A      Not assigned           Not assigned
2        M3A        North York              Parkwoods
3        M4A        North York       Victoria Village
4        M5A  Downtown Toronto           Harbourfront
..       ...               ...                    ...
282      M8Z         Etobicoke              Mimico NW
283      M8Z         Etobicoke     The Queensway West
284      M8Z         Etobicoke  Royal York South West
285      M8Z         Etobicoke         South of Bloor
286      M9Z      Not assigned           Not assigned

[287 rows x 3 columns]

### Cleaning the data

In [8]:
df_Na = df[df.Borough.isin(['Not assigned'])]

In [9]:
df_Na

    Postcode       Borough Neighbourhood
0        M1A  Not assigned  Not assigned
1        M2A  Not assigned  Not assigned
8        M8A  Not assigned  Not assigned
12       M2B  Not assigned  Not assigned
19       M7B  Not assigned  Not assigned
..       ...           ...           ...
277      M4Z  Not assigned  Not assigned
278      M5Z  Not assigned  Not assigned
279      M6Z  Not assigned  Not assigned
280      M7Z  Not assigned  Not assigned
286      M9Z  Not assigned  Not assigned

[77 rows x 3 columns]

In [10]:
df_Na = df[~df.Borough.isin(['Not assigned'])]

In [11]:
df_Na

    Postcode           Borough             Neighbourhood
2        M3A        North York                 Parkwoods
3        M4A        North York          Victoria Village
4        M5A  Downtown Toronto              Harbourfront
5        M6A        North York          Lawrence Heights
6        M6A        North York            Lawrence Manor
..       ...               ...                       ...
281      M8Z         Etobicoke  Kingsway Park South West
282      M8Z         Etobicoke                 Mimico NW
283      M8Z         Etobicoke        The Queensway West
284      M8Z         Etobicoke     Royal York South West
285      M8Z         Etobicoke            South of Bloor

[210 rows x 3 columns]

In [12]:
df_same_postcode = df_Na.groupby(['Postcode','Borough'])['Neighbourhood'].apply(','.join).reset_index()
df_same_postcode.tail(18)

    Postcode       Borough                                      Neighbourhood
85       M7A  Queen's Park                                       Not assigned
86       M7R   Mississauga              Canada Post Gateway Processing Centre
87       M7Y  East Toronto  Business Reply Mail Processing Centre 969 Eastern
88       M8V     Etobicoke         Humber Bay Shores,Mimico South,New Toronto
89       M8W     Etobicoke                              Alderwood,Long Branch
90       M8X     Etobicoke        The Kingsway,Montgomery Road,Old Mill North
91       M8Y     Etobicoke  Humber Bay,King's Mill Park,Kingsway Park Sout...
92       M8Z     Etobicoke  Kingsway Park South West,Mimico NW,The Queensw...
93       M9A  Queen's Park                                       Queen's Park
94       M9B     Etobicoke  Cloverdale,Islington,Martin Grove,Princess Gar...
95       M9C     Etobicoke  Bloordale Gardens,Eringate,Markland Wood,Old B...
96       M9L    North York                                      Humber Summit
97       M9M    North York                                    Emery,Humberlea
98       M9N          York                                             Weston
99       M9P     Etobicoke                                          Westmount
100      M9R     Etobicoke  Kingsview Village,Martin Grove Gardens,Richvie...
101      M9V     Etobicoke  Albion Gardens,Beaumond Heights,Humbergate,Jam...
102      M9W     Etobicoke                                          Northwest

In [13]:
df_same_postcode.loc[df_same_postcode['Neighbourhood']
                     =="Not assigned",'Neighbourhood'] = df_same_postcode.loc[df_same_postcode['Neighbourhood']
                                        =="Not assigned",'Borough']

In [14]:
df_same_postcode.tail(18)

    Postcode       Borough                                      Neighbourhood
85       M7A  Queen's Park                                       Queen's Park
86       M7R   Mississauga              Canada Post Gateway Processing Centre
87       M7Y  East Toronto  Business Reply Mail Processing Centre 969 Eastern
88       M8V     Etobicoke         Humber Bay Shores,Mimico South,New Toronto
89       M8W     Etobicoke                              Alderwood,Long Branch
90       M8X     Etobicoke        The Kingsway,Montgomery Road,Old Mill North
91       M8Y     Etobicoke  Humber Bay,King's Mill Park,Kingsway Park Sout...
92       M8Z     Etobicoke  Kingsway Park South West,Mimico NW,The Queensw...
93       M9A  Queen's Park                                       Queen's Park
94       M9B     Etobicoke  Cloverdale,Islington,Martin Grove,Princess Gar...
95       M9C     Etobicoke  Bloordale Gardens,Eringate,Markland Wood,Old B...
96       M9L    North York                                      Humber Summit
97       M9M    North York                                    Emery,Humberlea
98       M9N          York                                             Weston
99       M9P     Etobicoke                                          Westmount
100      M9R     Etobicoke  Kingsview Village,Martin Grove Gardens,Richvie...
101      M9V     Etobicoke  Albion Gardens,Beaumond Heights,Humbergate,Jam...
102      M9W     Etobicoke                                          Northwest

In [15]:
df_same_postcode.shape

(103, 3)

## Problem 2 Retrieving coorodinates

In [16]:
geo_url = "http://cocl.us/Geospatial_data"
geo_df = pd.read_csv(geo_url)

In [17]:
geo_df.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [18]:
df_same_postcode.rename(columns={'Postcode':'PostalCode'}, inplace=True)
geo_df.rename(columns={'Postal Code':'PostalCode'}, inplace=True)

In [19]:
geo_df.head()

  PostalCode   Latitude  Longitude
0        M1B  43.806686 -79.194353
1        M1C  43.784535 -79.160497
2        M1E  43.763573 -79.188711
3        M1G  43.770992 -79.216917
4        M1H  43.773136 -79.239476

In [21]:
merged_df = pd.merge(df_same_postcode, geo_df, on="PostalCode")

In [22]:
merged_df.head()

,PostalCode,Borough,Neighbourhood,Latitude,Longitude
0,M1B,Scarborough,"Rouge,Malvern",43.806686,-79.194353
1,M1C,Scarborough,"Highland Creek,Rouge Hill,Port Union",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood,Morningside,West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476

In [23]:
toronto_df = merged_df[merged_df['Borough'].str.contains("Toronto")]

In [24]:
toronto_df.head()

,PostalCode,Borough,Neighbourhood,Latitude,Longitude
37,M4E,East Toronto,The Beaches,43.676357,-79.293031
41,M4K,East Toronto,"The Danforth West,Riverdale",43.679557,-79.352188
42,M4L,East Toronto,"The Beaches West,India Bazaar",43.668999,-79.315572
43,M4M,East Toronto,Studio District,43.659526,-79.340923
44,M4N,Central Toronto,Lawrence Park,43.728020,-79.388790

In [29]:
CLIENT_ID = 'NXQUJA24WEL3B2LCND2DET4V0SUVN5KPE33IJYB50NBIR22D' # your Foursquare ID
CLIENT_SECRET = 'JQ1RMZTXKI2SA2JPB2NKFZURXWQJVALQMB1RWXGPGRRALJAQ' # your Foursquare Secret
VERSION = '20180604'
LIMIT = 30
print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: NXQUJA24WEL3B2LCND2DET4V0SUVN5KPE33IJYB50NBIR22D
CLIENT_SECRET:JQ1RMZTXKI2SA2JPB2NKFZURXWQJVALQMB1RWXGPGRRALJAQ

In [31]:
def getNearbyVenues(names, latitudes, longitudes):
    radius=500
    LIMIT=100
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
        
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)

        results = requests.get(url).json()["response"]['groups'][0]['items']
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)
toronto_venues = getNearbyVenues(names=toronto_df['Neighbourhood'],
                                   latitudes=toronto_df['Latitude'],
                                   longitudes=toronto_df['Longitude']
                                  )

The Beaches
The Danforth West,Riverdale
The Beaches West,India Bazaar
Studio District
Lawrence Park
Davisville North
North Toronto West
Davisville
Moore Park,Summerhill East
Deer Park,Forest Hill SE,Rathnelly,South Hill,Summerhill West
Rosedale
Cabbagetown,St. James Town
Church and Wellesley
Harbourfront
Ryerson,Garden District
St. James Town
Berczy Park
Central Bay Street
Adelaide,King,Richmond
Harbourfront East,Toronto Islands,Union Station
Design Exchange,Toronto Dominion Centre
Commerce Court,Victoria Hotel
Roselawn
Forest Hill North,Forest Hill West
The Annex,North Midtown,Yorkville
Harbord,University of Toronto
Chinatown,Grange Park,Kensington Market
CN Tower,Bathurst Quay,Island airport,Harbourfront West,King and Spadina,Railway Lands,South Niagara
Stn A PO Boxes 25 The Esplanade
First Canadian Place,Underground city
Christie
Dovercourt Village,Dufferin
Little Portugal,Trinity
Brockton,Exhibition Place,Parkdale Village
High Park,The Junction South
Parkdale,Roncesvalles
Runnymede,Swansea
Business Reply Mail Processing Centre 969 Eastern

In [32]:
toronto_venues.head()

,Neighborhood,Neighborhood Latitude,Neighborhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
0,The Beaches,43.676357,-79.293031,Glen Manor Ravine,43.676821,-79.293942,Trail
1,The Beaches,43.676357,-79.293031,The Big Carrot Natural Food Market,43.678879,-79.297734,Health Food Store
2,The Beaches,43.676357,-79.293031,Grover Pub and Grub,43.679181,-79.297215,Pub
3,The Beaches,43.676357,-79.293031,Upper Beaches,43.680563,-79.292869,Neighborhood
4,"The Danforth West,Riverdale",43.679557,-79.352188,Pantheon,43.677621,-79.351434,Greek Restaurant

In [33]:
toronto_venues.groupby('Neighborhood').count()

,Neighborhood Latitude,Neighborhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
Neighborhood,,,,,,
"Adelaide,King,Richmond",100,100,100,100,100,100
Berczy Park,56,56,56,56,56,56
"Brockton,Exhibition Place,Parkdale Village",23,23,23,23,23,23
Business Reply Mail Processing Centre 969 Eastern,17,17,17,17,17,17
"CN Tower,Bathurst Quay,Island airport,Harbourfront West,King and Spadina,Railway Lands,South Niagara",14,14,14,14,14,14
"Cabbagetown,St. James Town",44,44,44,44,44,44
Central Bay Street,82,82,82,82,82,82
"Chinatown,Grange Park,Kensington Market",96,96,96,96,96,96
Christie,18,18,18,18,18,18
Church and Wellesley,87,87,87,87,87,87
"Commerce Court,Victoria Hotel",100,100,100,100,100,100
Davisville,39,39,39,39,39,39
Davisville North,7,7,7,7,7,7
"Deer Park,Forest Hill SE,Rathnelly,South Hill,Summerhill West",15,15,15,15,15,15
"Design Exchange,Toronto Dominion Centre",100,100,100,100,100,100
"Dovercourt Village,Dufferin",16,16,16,16,16,16
"First Canadian Place,Underground city",100,100,100,100,100,100
"Forest Hill North,Forest Hill West",4,4,4,4,4,4
"Harbord,University of Toronto",37,37,37,37,37,37
Harbourfront,49,49,49,49,49,49
"Harbourfront East,Toronto Islands,Union Station",100,100,100,100,100,100
"High Park,The Junction South",25,25,25,25,25,25
Lawrence Park,4,4,4,4,4,4
"Little Portugal,Trinity",64,64,64,64,64,64
"Moore Park,Summerhill East",4,4,4,4,4,4
North Toronto West,22,22,22,22,22,22
"Parkdale,Roncesvalles",15,15,15,15,15,15
Rosedale,4,4,4,4,4,4
Roselawn,1,1,1,1,1,1
"Runnymede,Swansea",37,37,37,37,37,37
"Ryerson,Garden District",100,100,100,100,100,100
St. James Town,100,100,100,100,100,100
Stn A PO Boxes 25 The Esplanade,99,99,99,99,99,99
Studio District,37,37,37,37,37,37
"The Annex,North Midtown,Yorkville",22,22,22,22,22,22
The Beaches,4,4,4,4,4,4
"The Beaches West,India Bazaar",19,19,19,19,19,19
"The Danforth West,Riverdale",42,42,42,42,42,42